name: CLI

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Prettier
    types:
      - completed

jobs:
  test-evm:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: docker build -f Dockerfile.cli --target cli-local-test . --progress=plain

  test-solana:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: tilt-kube-public
    steps:
      - uses: actions/checkout@v5
      - run: docker build -f Dockerfile.cli --target cli-local-test-solana . --progress=plain
